sudo: false
language: node_js

node_js:
  - 10 # use nodejs v10 LTS

cache: npm

branches:
  only:
    - dandan_mainpage # build dandan_mainpage branch only

install:
  - bash install.sh

cache:
  directories:
    - node_modules

script:
#  - hexo g
  - bash generate.sh

after_script:
  - cd  hexo/public
  - git init
  - git config user.name "dandan"
  - git config user.email "ry.socket@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${repo_taken}@${GH_REF}" master:master

env:
 global:
   - GH_REF: github.com/ElegantDandan/ElegantDandan.github.io.git