sudo: false
language: node_js

node_js:
  - 10 # use nodejs v10 LTS

cache: npm

branches:
  only:
    - dandan_mainpage # build dandan_mainpage branch only

install:
  - bash install.sh

script:
#  - hexo generate # generate static files
  - bash generate.sh

after_script:
  - cd ./hexo
  - hexo d
  
env:
 global:
   - GH_REF: github.com/ElegantDandan/ElegantDandan.github.io.git --{仓库地址}