sudo: false
language: node_js

node_js:
  - 10 # use nodejs v10 LTS

cache: npm

branches:
  only:
    - dandan_mainpage # build dandan_mainpage branch only

script:
#  - hexo generate # generate static files
  - bash generate.sh

after_script:
  - cd ./public
  - git init
  - git config user.name "dandan" --{GitHub账户名称}
  - git config user.email "ry.socket@gmail.com" --{Github账户邮箱}
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
 global:
   - GH_REF: github.com/ElegantDandan/ElegantDandan.github.io.git --{仓库地址}