sudo: false
language: node_js

node_js:
- 12

cache:
  directories:
  - node_modules

branches:
  only:
  - dandan_mainpage

before_install:
- openssl aes-256-cbc -K $encrypted_0d170fcd25c4_key -iv $encrypted_0d170fcd25c4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

install:
- bash install.sh

script:
- bash generate.sh

after_script:
- cd hexo
- hexo d
